index:
  path: /dashboard/settings
  controller: Selene\Modules\SettingsModule\Http\Controllers\SettingsController@index
  methods:
    - GET
  permission: SettingsModule

create:
  path: /dashboard/settings/create
  controller: Selene\Modules\SettingsModule\Http\Controllers\SettingsController@create
  methods:
    - GET
  permission: SettingsModule.add

store:
  path: /dashboard/settings/store
  controller: Selene\Modules\SettingsModule\Http\Controllers\SettingsController@store
  methods:
    - POST
  permission: SettingsModule.add

edit:
  path: /dashboard/settings/{{setting}}/edit
  controller: Selene\Modules\SettingsModule\Http\Controllers\SettingsController@edit
  methods:
    - GET
  permission: SettingsModule.edit

update:
  path: /dashboard/settings/{{setting}}
  controller: Selene\Modules\SettingsModule\Http\Controllers\SettingsController@update
  methods:
    - PUT
    - PATCH
  permission: SettingsModule.edit